language: python
python:
- '3.6'
install:
- pip install -r requirements.txt
- pip install pytest
- pip install codecov
- pip install pytest-cov
script:
- py.test --cov=trees tests/*_u.py
after_success:
- codecov
deploy:
  provider: pypi
  user: kariminf
  on:
    python: '3.6'
  password:
    secure: r/MopkgmnuKiqNYV26d9Xok9q3VlIVWwiRzqv9U2fr67scmvzbWtWcg6mpqaGp00Qfwb4ANA849CQ1BRNLc6P0s+4PFMsb1Ei7YAbAgOcf6d3fZ95rVLfJI/1XvFzK5Z+JPWPeeRyvC79aH1tfm765KJcq0bEoBsaZHBj60rkdu/FBGxb1OYi4iyGdhjBuTA8jiNxiVK0O+gSF7cHN24OB/AhtYB0MVziElw8uJENUWBiDqPkE6JctkUHRU5ohrCQMlpzC/nROvft80PhuxGqdFeinqgQRtfqi3a+N+nqE3rXfVprQKlwkWGuvWvNaCAJ9nSLZ8LfxQ6iD6XwAIMlaM41QHlBM3/+Tunj+EkVdHRqCeCYzQk+WlPQ2K0UMNO8qsgwMBl+NddrJBlFOVSyp6XuSIcR0L7aHqAEPNguAE4PAfxqOa6Kkz62xy3fEfHU0LX7G6Rxirthduz06Taacv3lIeEx7BmuevuxIV9Vhr9wpNJ4bvwiRKjrad5buN6gORvinlWP8UNN6cn0bU+Akni9GT49J/xy68s6qNTGDNQUVRfQqTAKGB4IgJH/mt8YnvmDtSo9faJ8Dx90ouXHTY8Lh0jT689fhJjI86insDwu5moD0tA3D1mmVe89RZ993x0VK+li5ikMa065SEQaYgRLh9VOoR7sB0aC5ALj7E=
